export const offices = [
  { id: "33", name: "Alghero Aeroporto - AHO", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "75", name: "Ancona Aeroporto - AOI", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "43", name: "Bari Aeroporto - BRI", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "72", name: "Bergamo Aeroporto - BGY", descr: "Desk in terminal", electric_cars: 1 }, 
  { id: "24", name: "Bologna Aeroporto - BLQ", descr: "Desk in Terminal", electric_cars: 0 }, 
  { id: "64", name: "Bologna", descr: "40121 - Viale Pietramellara,  37", electric_cars: 0 }, 
  { id: "22", name: "Bolzano", descr: "Viale Galileo Galilei,  10/H", electric_cars: 0 }, 
  { id: "51", name: "Brescia", descr: "25122 - Via della Stazione,  49", electric_cars: 1 }, 
  { id: "53", name: "Brindisi Aeroporto - BDS", descr: "Desk in Rent a Car area", electric_cars: 0 }, 
  { id: "34", name: "Cagliari Aeroporto - CAG", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "94", name: "Catania Aeroporto - CTA", descr: "Desk in Rent a Car area", electric_cars: 0 }, 
  { id: "93", name: "Comiso Aeroporto - CIY", descr: "Desk in arrivals hall", electric_cars: 0 }, 
  { id: "23", name: "Firenze Aeroporto - FLR", descr: "Palagio degli Spini area", electric_cars: 0 }, 
  { id: "19", name: "Firenze", descr: "50123 - Via Borgognissanti,  100\/R", electric_cars: 0 }, 
  { id: "28", name: "Genova Aeroporto - GOA", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "96", name: "Giardini Naxos", descr: "98135 - Via Recanati,  21", electric_cars: 0 }, 
  { id: "26", name: "Lamezia Aeroporto - SUF", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "74", name: "Lanciano", descr: "66034 - Viale delle Rimembranze,  31", electric_cars: 0 }, 
  { id: "80", name: "Messina", descr: "98122 - Via Vittorio Emanuele II,  7", electric_cars: 0 }, 
  { id: "14", name: "Milano Linate - LIN", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "15", name: "Milano Malpensa T1 - MXP", descr: "Desk in Terminal 1", electric_cars: 1 }, 
  { id: "32", name: "Milano (via Doria)", descr: "20124 - Viale Andrea Doria,  46", electric_cars: 1 }, 
  { id: "16", name: "Milano (via Pisani)", descr: "20124 - Via Vittor Pisani,  7", electric_cars: 1 }, 
  { id: "10", name: "Milazzo", descr: "98057 - Via Tindaro La Rosa,  24", electric_cars: 0 }, 
  { id: "18", name: "Napoli Aeroporto - NAP", descr: "Desk in Rent a Car area", electric_cars: 0 }, 
  { id: "47", name: "Olbia Aeroporto - OLB", descr: "Desk in Rent a Car area", electric_cars: 0 }, 
  { id: "91", name: "Palermo Aeroporto - PMO", descr: "Desk in Rent a Car area", electric_cars: 1 }, 
  { id: "46", name: "Palermo (via Napoli)", descr: "90144 - Via Napoli,  90", electric_cars: 1 }, 
  { id: "92", name: "Palermo (via Stabile)", descr: "90139 - Via Mariano Stabile,  6\/A", electric_cars: 1 }, 
  { id: "27", name: "Pantelleria Aeroporto - PNL", descr: "Desk in arrivals hall", electric_cars: 0 }, 
  { id: "40", name: "Perugia Aeroporto - PEG", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "39", name: "Perugia", descr: "06124 - Via Settevalli,  4", electric_cars: 0 }, 
  { id: "71", name: "Pescara Aeroporto - PSR", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "20", name: "Pisa Aeroporto - PSA", descr: "Desk in Rent a Car area", electric_cars: 0 }, 
  { id: "68", name: "R. Calabria Aeroporto - REG", descr: "Desk in Rent a Car area", electric_cars: 0 }, 
  { id: "69", name: "R. Calabria", descr: "89127 - Via Aspromonte,  18\/C", electric_cars: 0 }, 
  { id: "78", name: "Rimini Aeroporto - RMI", descr: "47924 - Via Flaminia,  409", electric_cars: 0 }, 
  { id: "25", name: "Roma Ciampino - CIA", descr: "Desk in Rent a Car area", electric_cars: 1 }, 
  { id: "21", name: "Roma (via Teulada)", descr: "00185 - Via Teulada,  57\/59", electric_cars: 1 }, 
  { id: "11", name: "Roma Fiumicino - FCO", descr: "Desk in terminal", electric_cars: 1 }, 
  { id: "63", name: "Roma Termini", descr: "00185 - Via Giovanni Giolitti,  34", electric_cars: 1 }, 
  { id: "17", name: "Salerno", descr: "84123 - Piazza Vittorio Veneto,  36", electric_cars: 0 }, 
  { id: "38", name: "Siracusa", descr: "96100 - Corso Umberto I n. 90", electric_cars: 0 }, 
  { id: "52", name: "Torino Aeroporto - TRN", descr: "Desk in terminal", electric_cars: 1 }, 
  { id: "29", name: "Torino (Beinasco)", descr: "10092 - Strada Orbassano,  16\/18", electric_cars: 1 }, 
  { id: "30", name: "Torino (Lingotto)", descr: "10126 - Via Nizza,  294 (c\/o Lingotto Fiere)", electric_cars: 1 }, 
  { id: "84", name: "Trapani Aeroporto - TPS", descr: "Desk in Rent a Car area arrivals hall", electric_cars: 0 }, 
  { id: "73", name: "Treviso Aeroporto - TSF", descr: "Desk in terminal", electric_cars: 0 }, 
  { id: "66", name: "Trieste Aeroporto - TRS", descr: "34077 - Via Aquileia,  46 - Ronchi dei Legionari (GO)", electric_cars: 0 }, 
  { id: "41", name: "Venezia Aeroporto - VCE", descr: "P1 Parking", electric_cars: 0 }, 
  { id: "48", name: "Verona Aeroporto - VRN", descr: "Desk in Rent a Car area", electric_cars: 0 }
];